### ISSUE TITLE
Why promises?

### ISSUE THREAD

**Issue by DominikGuzei** [smebberson/array-sync#16]
Thanks for the package, looks like what i need for a current project … im wondering why you implemented it as a promise based api though?

**Comment by smebberson** [comment]
You're right, there is no need for the promise based api though. You can raise a PR if you like and I'd be happy to do a major release. Are you interested in doing that?

**Comment by DominikGuzei** [comment]
Hey @smebberson, it's not high priority but maybe i will find some time in the coming months 😉

**Comment by smebberson** [comment]
I've done it :)

https://github.com/smebberson/array-sync/pull/17

**Comment by DominikGuzei** [comment]
Awesome, thanks for the prompt update - will test the new version asap! Great setup improvements too 😉

**Comment by smebberson** [comment]
No worries, let me know if you find any issues. I've hooked up Dependabot too.
