### ISSUE TITLE
Get rid of Bluebird (or at least make it optional)

### ISSUE THREAD

**Issue by p-bakker** [smebberson/array-sync#7]
This module doesn't seem to use any bluebird functionality that isn't supported by native promises.

As Bluebird does not play nice with for example async_hooks in Node, this module cannot be used in combination with an other package that uses stuff like async_hooks.
Please consider removing the dependancy on bluebird or at least make the Promise implementation to use configurable

**Comment by smebberson** [comment]
Bluebird was being used to implement the Promise or Callback support. I decided to remove it entirely and use native Promises, removing callback support altogether. https://github.com/smebberson/array-sync/pull/9

That's all merged in now and v3.0.0 is released :)
